bind = $mainMod, Left, movefocus, l
bind = $mainMod, Down, movefocus, d
bind = $mainMod, Up, movefocus, u
bind = $mainMod, Right, movefocus, r

bind = $mainMod SHIFT, Left, swapwindow, l
bind = $mainMod SHIFT, Down, swapwindow, d
bind = $mainMod SHIFT, Up, swapwindow, u
bind = $mainMod SHIFT, Right, swapwindow, r

binde = $mainMod CTRL, Left, resizeactive, -20 0
binde = $mainMod CTRL, Down, resizeactive, 0 20
binde = $mainMod CTRL, Up, resizeactive, 0 -20
binde = $mainMod CTRL, Right, resizeactive, 20 0

bind = ALT, Down, changegroupactive, b
bind = ALT, Up, changegroupactive, f
