bind = $mainMod, H, movefocus, l
bind = $mainMod, J, movefocus, d
bind = $mainMod, K, movefocus, u
bind = $mainMod, L, movefocus, r

bind = $mainMod SHIFT, H, swapwindow, l
bind = $mainMod SHIFT, J, swapwindow, d
bind = $mainMod SHIFT, K, swapwindow, u
bind = $mainMod SHIFT, L, swapwindow, r

binde = $mainMod CTRL, H, resizeactive, -20 0
binde = $mainMod CTRL, J, resizeactive, 0 20
binde = $mainMod CTRL, K, resizeactive, 0 -20
binde = $mainMod CTRL, L, resizeactive, 20 0

bind = ALT, G, togglegroup
bind = ALT, J, changegroupactive, b
bind = ALT, K, changegroupactive, f
