monitor=,1920x1080@360,auto,auto

$terminal = ghostty
$fileManager = dolphin

exec-shutdown = rm -rf /run/user/1000/hypr/$HYPRLAND_INSTANCE_SIGNATURE
exec-once = nsh
exec-once = swww-daemon
exec-once = wayscriber --daemon
exec-once = gnome-keyring-daemon --start --components=secrets,ssh
exec-once = wl-clip-persist --clipboard regular --all-mime-type-regex '(?i)^(?!(?:image|audio|video|font|model)/).+'
exec-once = kbuildsycoca6
exec-once = baloo_file6
exec-once = solaar --window=hide
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

env = __GL_MaxFramesAllowed,1
env = __GL_GSYNC_ALLOWED,0
env = XCURSOR_THEME,Bibata-Modern-Ice
env = HYPRCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt6ct
env = XDG_MENU_PREFIX,arch-

source = ~/.config/hypr/ui.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/devices.conf

# MCSR config
# source = ~/.config/hypr/mcsr.conf
