bind -n M-Left  if-shell "$is_vim" 'send-keys C-h' 'select-pane -L'
bind -n M-Down  if-shell "$is_vim" 'send-keys C-j' 'select-pane -D'
bind -n M-Up    if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
bind -n M-Right if-shell "$is_vim" 'send-keys C-l' 'select-pane -R'

bind | split-window -c '#{pane_current_path}' -h
bind ^ split-window -c '#{pane_current_path}' -v

unbind -T prefix Up
unbind -T prefix Down
unbind -T prefix Left
unbind -T prefix Right

unbind -T prefix M-Up
unbind -T prefix M-Down
unbind -T prefix M-Left
unbind -T prefix M-Right

bind -r C-Left  resize-pane -L 5
bind -r C-Down  resize-pane -D 5
bind -r C-Up    resize-pane -U 5
bind -r C-Right resize-pane -R 5
