[tools]
usage = "latest"
node = "lts"
go = "latest"
zig = "master"
rust = "stable"
lua = "5.4.7"

[env]
ASDF_LUA_LUAROCKS_VERSION = "3.11.1"

[settings]
disable_tools = ["python"]
idiomatic_version_file_enable_tools = ["node"]

[settings.zig]
use_community_mirrors = true
