-- hs.loadSpoon("EmmyLua")
require("keyboard.yabai")
require("keyboard.arrows")
require("keyboard.apps")
require("auto-reload")
hs.notify.new({ title = "Hammerspoon", informativeText = "Ready to rock!! 🤘" }):send()
