import Gio from "gi://Gio?version=2.0";
import GLib from "gi://GLib?version=2.0";

import { writeFileAsync } from "ags/file";
import { execAsync } from "ags/process";

export type ColorData = {
	name?: string;
	wallpaper?: string;
	accent?: string;
	special: {
		background: string;
		foreground: string;
		cursor: string;
	};
	colors: {
		color0: string;
		color1: string;
		color2: string;
		color3: string;
		color4: string;
		color5: string;
		color6: string;
		color7: string;
		color8: string;
		color9: string;
		color10: string;
		color11: string;
		color12: string;
		color13: string;
		color14: string;
		color15: string;
	};
};

const stripHash = (hex: string) => hex.replace(/^#/, "");

export function reloadTmux(): void {
	const colorsPath = `${GLib.get_user_cache_dir()}/novashell/tmux-colors.conf`;
	execAsync(["tmux", "source-file", colorsPath])
		.then(() => {
			execAsync([
				"bash", "-c",
				"tmux list-clients -F '#{client_name}' | while read c; do tmux refresh-client -t \"$c\" -S; done",
			]).catch(() => {});
		})
		.catch(() => {});
}

const NOVASHELL_TO_NVIM_THEME: Record<string, string> = {
	"Tokyo Night": "Tokyo Night",
	Everforest: "Everforest",
	"Catppuccin Mocha": "Catppuccin",
};

export function reloadNeovim(themeName?: string): void {
	const nvimTheme = (themeName && NOVASHELL_TO_NVIM_THEME[themeName]) || "System (pywal)";
	const escaped = nvimTheme.replace(/'/g, "\\'");
	execAsync([
		"bash", "-c",
		`for sock in /run/user/1000/nvim.*.0; do [ -e "$sock" ] && nvim --server "$sock" --remote-send ':lua require("core.colorscheme").apply("${escaped}")<CR>' 2>/dev/null; done`,
	])
		.then(() => {})
		.catch(() => {});
}

export function reloadFish(): void {
	const walCachePath = `${GLib.get_user_cache_dir()}/wal/colors.fish`;
	execAsync(["fish", "-c", `source ${walCachePath}`])
		.then(() => {})
		.catch(() => {});
}

/** Broadcast terminal color changes via OSC escape sequences to all PTYs.
 * Uses Python (same approach as pywal) for reliable escape byte writing. */
export function broadcastTerminalColors(data: ColorData): void {
	const parts: string[] = [];

	for (let i = 0; i <= 15; i++) {
		const key = `color${i}` as keyof typeof data.colors;
		if (data.colors[key]) parts.push(`\\033]4;${i};${data.colors[key]}\\007`);
	}

	parts.push(`\\033]10;${data.special.foreground}\\007`);
	parts.push(`\\033]12;${data.special.cursor}\\007`);

	const seq = parts.join("");

	execAsync([
		"python3", "-c",
		`import glob,os\nseq="${seq}"\nseq=seq.encode().decode("unicode_escape")\ncount=0\nfor t in glob.glob("/dev/pts/[0-9]*"):\n try:\n  with open(t,"w") as f: f.write(seq); count+=1\n except: pass\nprint(count)`,
	])
		.then(() => {})
		.catch((e) => console.error(`ColorUtils: Broadcast failed: ${e}`));
}

export async function generateTmuxColors(data: ColorData): Promise<void> {
	const colors = data.colors;
	const special = data.special;
	const accent = data.accent || colors.color4;
	const surface = adjustLightness(special.background, 15);

	const tmuxColors = `# Generated by novashell
set -g pane-border-style "fg=${colors.color8}"
set -g pane-active-border-style "fg=${accent}"
set -g pane-border-lines single
set -g pane-border-indicators off
set -g message-style "fg=${special.foreground},bg=default"
set -g window-status-format "#[fg=${special.background},bg=${colors.color8}] #I #[fg=${special.foreground},bg=${surface}] #{b:pane_current_path} "
set -g window-status-current-format "#[fg=${special.background},bg=${accent}] #I #[fg=${special.foreground},bg=${surface}] #{b:pane_current_path} "
set-window-option -g window-status-separator " "
`;

	const cacheDir = `${GLib.get_user_cache_dir()}/novashell`;
	const cacheDirFile = Gio.File.new_for_path(cacheDir);
	if (!cacheDirFile.query_exists(null)) {
		cacheDirFile.make_directory_with_parents(null);
	}

	await writeFileAsync(`${cacheDir}/tmux-colors.conf`, tmuxColors).catch(
		(e) => {
			console.error(`ColorUtils: Could not write tmux colors: ${e}`);
		},
	);
}

export async function generateFishColors(data: ColorData): Promise<void> {
	const c = data.colors;
	const s = data.special;

	const fishColors = `# Generated by novashell - Theme: ${data.name || "pywal"}
# Uses universal variables (-U) so changes propagate to all running fish sessions

set -U fish_color_normal ${stripHash(s.foreground)}
set -U fish_color_command ${stripHash(c.color4)}
set -U fish_color_keyword ${stripHash(c.color5)}
set -U fish_color_quote ${stripHash(c.color2)}
set -U fish_color_redirection ${stripHash(c.color6)}
set -U fish_color_end ${stripHash(c.color5)}
set -U fish_color_error ${stripHash(c.color1)}
set -U fish_color_param ${stripHash(c.color6)}
set -U fish_color_comment ${stripHash(c.color8)}
set -U fish_color_selection --background=${stripHash(c.color8)}
set -U fish_color_search_match --background=${stripHash(c.color8)}
set -U fish_color_operator ${stripHash(c.color6)}
set -U fish_color_escape ${stripHash(c.color5)}
set -U fish_color_autosuggestion ${stripHash(c.color8)}
set -U fish_color_cwd ${stripHash(c.color4)}
set -U fish_color_user ${stripHash(c.color2)}
set -U fish_color_host ${stripHash(c.color4)}
set -U fish_color_host_remote ${stripHash(c.color3)}
set -U fish_color_cancel ${stripHash(c.color1)}

set -U fish_pager_color_progress ${stripHash(c.color8)}
set -U fish_pager_color_prefix ${stripHash(c.color4)}
set -U fish_pager_color_completion ${stripHash(s.foreground)}
set -U fish_pager_color_description ${stripHash(c.color8)}
`;

	const walCachePath = `${GLib.get_user_cache_dir()}/wal/colors.fish`;
	await writeFileAsync(walCachePath, fishColors).catch((e) => {
		console.error(`ColorUtils: Could not write fish colors: ${e}`);
	});
}

export function updateHyprlandColors(data: ColorData): void {
	const accent = (data.accent || data.colors.color4).replace(/^#/, "");
	const inactive = data.colors.color8.replace(/^#/, "");

	execAsync(`hyprctl keyword general:col.active_border "rgb(${accent})"`).catch(
		() => {
			/* Hyprland might not be running */
		},
	);

	execAsync(
		`hyprctl keyword general:col.inactive_border "rgb(${inactive})"`,
	).catch(() => {
		/* Hyprland might not be running */
	});
}

/** Adjust lightness of a hex color by a fixed amount (-255 to +255) */
export function adjustLightness(hex: string, amount: number): string {
	const h = hex.replace(/^#/, "");
	const r = Math.max(
		0,
		Math.min(255, parseInt(h.substring(0, 2), 16) + amount),
	);
	const g = Math.max(
		0,
		Math.min(255, parseInt(h.substring(2, 4), 16) + amount),
	);
	const b = Math.max(
		0,
		Math.min(255, parseInt(h.substring(4, 6), 16) + amount),
	);
	return `#${r.toString(16).padStart(2, "0")}${g.toString(16).padStart(2, "0")}${b.toString(16).padStart(2, "0")}`;
}

export async function updateGhosttyColors(data: ColorData): Promise<void> {
	const colors = data.colors;
	const special = data.special;

	const lines: string[] = [];

	for (let i = 0; i <= 15; i++) {
		const colorKey = `color${i}` as keyof typeof colors;
		if (colors[colorKey]) {
			lines.push(`palette = ${i}=${colors[colorKey]}`);
		}
	}

	lines.push(``);
	lines.push(`background = ${special.background}`);
	lines.push(`foreground = ${special.foreground}`);
	lines.push(`cursor-color = ${special.cursor}`);
	lines.push(`selection-background = ${colors.color8}`);
	lines.push(`selection-foreground = ${special.foreground}`);

	const content = lines.join("\n") + "\n";
	const ghosttyColorsPath = `${GLib.get_user_config_dir()}/ghostty/colors`;

	// Write to temp file, then `cp` to target. `cp` writes in-place (same inode),
	// which fires IN_MODIFY + IN_CLOSE_WRITE so Ghostty's inotify watcher detects changes.
	// writeFileAsync / Gio.File.replace use atomic temp+rename which invalidates the watch.
	const tmpPath = `${GLib.get_tmp_dir()}/novashell-ghostty-colors`;
	await writeFileAsync(tmpPath, content).catch((e: Error) => {
		console.error(`ColorUtils: Failed to write ghostty temp: ${e.message}`);
	});
	await execAsync(["cp", "--", tmpPath, ghosttyColorsPath]).catch((e: Error) => {
		console.error(`ColorUtils: Failed to cp ghostty colors: ${e.message}`);
	});

	reloadGhostty();
}

function reloadGhostty(): void {
	execAsync([
		"bash", "-c",
		`hyprctl clients -j | jq -r '.[] | select(.class == "com.mitchellh.ghostty") | .address' | while read addr; do hyprctl dispatch sendshortcut "CTRL SHIFT, comma, address:$addr" 2>/dev/null; done`,
	])
		.then(() => {})
		.catch(() => {});
}

export async function updateBtopColors(data: ColorData): Promise<void> {
	const c = data.colors;
	const s = data.special;

	const btopTheme = `# Generated by novashell
# Wallpaper: ${data.wallpaper}

# Main background, empty for terminal default
theme[main_bg]=""

# Main text color
theme[main_fg]="${s.foreground}"

# Title color for boxes
theme[title]="${s.foreground}"

# Highlight color for keyboard shortcuts
theme[hi_fg]="${c.color4}"

# Background color of selected item in processes box
theme[selected_bg]="${c.color4}"

# Foreground color of selected item in processes box
theme[selected_fg]="${s.background}"

# Color of inactive/disabled text
theme[inactive_fg]="${c.color8}"

# Color of text appearing on top of graphs
theme[graph_text]="${s.foreground}"

# Background color of the percentage meters
theme[meter_bg]="${c.color8}"

# Misc colors for processes box including mini cpu graphs
theme[proc_misc]="${c.color5}"

# Cpu box outline color
theme[cpu_box]="${c.color4}"

# Memory/disks box outline color
theme[mem_box]="${c.color2}"

# Net up/down box outline color
theme[net_box]="${c.color1}"

# Processes box outline color
theme[proc_box]="${c.color6}"

# Box divider line and small boxes line color
theme[div_line]="${c.color8}"

# Temperature graph colors
theme[temp_start]="${c.color4}"
theme[temp_mid]="${c.color5}"
theme[temp_end]="${c.color1}"

# CPU graph colors
theme[cpu_start]="${c.color4}"
theme[cpu_mid]="${c.color6}"
theme[cpu_end]="${c.color2}"

# Mem/Disk free meter
theme[free_start]="${c.color2}"
theme[free_mid]="${c.color6}"
theme[free_end]="${c.color4}"

# Mem/Disk cached meter
theme[cached_start]="${c.color5}"
theme[cached_mid]="${c.color4}"
theme[cached_end]="${c.color6}"

# Mem/Disk available meter
theme[available_start]="${c.color3}"
theme[available_mid]="${c.color2}"
theme[available_end]="${c.color6}"

# Mem/Disk used meter
theme[used_start]="${c.color1}"
theme[used_mid]="${c.color5}"
theme[used_end]="${c.color4}"

# Download graph colors
theme[download_start]="${c.color4}"
theme[download_mid]="${c.color2}"
theme[download_end]="${c.color6}"

# Upload graph colors
theme[upload_start]="${c.color5}"
theme[upload_mid]="${c.color1}"
theme[upload_end]="${c.color3}"
`;

	const btopThemesDir = Gio.File.new_for_path(
		`${GLib.get_user_config_dir()}/btop/themes`,
	);
	if (!btopThemesDir.query_exists(null)) {
		btopThemesDir.make_directory_with_parents(null);
	}

	const btopThemePath = `${GLib.get_user_config_dir()}/btop/themes/pywal.theme`;
	await writeFileAsync(btopThemePath, btopTheme).catch((e: Error) => {
		console.error(`ColorUtils: Failed to write btop theme: ${e.message}`);
	});
}

export async function updateGtkColors(data: ColorData): Promise<void> {
	const s = data.special;
	const c = data.colors;
	const accent = data.accent || c.color4;

	const viewBg = adjustLightness(s.background, 8);
	const cardBg = adjustLightness(s.background, 13);
	const popoverBg = adjustLightness(s.background, 8);

	const css = `/* Generated by novashell - Theme: ${data.name || "pywal"} */
@define-color accent_bg_color ${accent};
@define-color accent_fg_color ${s.foreground};
@define-color accent_color ${accent};
@define-color destructive_bg_color ${c.color1};
@define-color destructive_fg_color ${s.foreground};
@define-color success_bg_color ${c.color2};
@define-color success_fg_color ${s.foreground};
@define-color warning_bg_color ${c.color3};
@define-color warning_fg_color ${s.background};
@define-color window_bg_color ${s.background};
@define-color window_fg_color ${s.foreground};
@define-color view_bg_color ${viewBg};
@define-color view_fg_color ${s.foreground};
@define-color headerbar_bg_color ${c.color0};
@define-color headerbar_fg_color ${s.foreground};
@define-color card_bg_color ${cardBg};
@define-color card_fg_color ${s.foreground};
@define-color dialog_bg_color ${s.background};
@define-color dialog_fg_color ${s.foreground};
@define-color popover_bg_color ${popoverBg};
@define-color popover_fg_color ${s.foreground};
@define-color sidebar_bg_color ${c.color0};
@define-color sidebar_fg_color ${s.foreground};
`;

	for (const dir of ["gtk-4.0", "gtk-3.0"]) {
		const dirPath = `${GLib.get_user_config_dir()}/${dir}`;
		const dirFile = Gio.File.new_for_path(dirPath);
		if (!dirFile.query_exists(null)) {
			dirFile.make_directory_with_parents(null);
		}
		await writeFileAsync(`${dirPath}/gtk.css`, css).catch((e: Error) => {
			console.error(`ColorUtils: Failed to write ${dir}/gtk.css: ${e.message}`);
		});
	}
}

export async function updateQtColors(data: ColorData): Promise<void> {
	const s = data.special;
	const c = data.colors;
	const accent = data.accent || c.color4;

	const toArgb = (hex: string) => `#ff${stripHash(hex)}`;
	const toArgbAlpha = (hex: string, alpha: string) =>
		`#${alpha}${stripHash(hex)}`;

	const buttonBg = adjustLightness(c.color0, 10);
	const light = adjustLightness(c.color0, 51);
	const midlight = adjustLightness(c.color0, 26);
	const dark = adjustLightness(s.background, -20);
	const altBase = adjustLightness(s.background, 8);

	// 22 values per line: WindowText, Button, Light, Midlight, Dark, Mid, Text,
	// BrightText, ButtonText, Base, Window, Shadow, Highlight, HighlightedText,
	// Link, LinkVisited, AlternateBase, ToolTipBase, ToolTipText, PlaceholderText,
	// Accent, (padding)
	const activeLine = [
		toArgb(s.foreground), // 0  WindowText
		toArgb(buttonBg), // 1  Button
		toArgb(light), // 2  Light
		toArgb(midlight), // 3  Midlight
		toArgb(dark), // 4  Dark
		toArgb(c.color8), // 5  Mid
		toArgb(s.foreground), // 6  Text
		toArgb(s.foreground), // 7  BrightText
		toArgb(s.foreground), // 8  ButtonText
		toArgb(s.background), // 9  Base
		toArgb(s.background), // 10 Window
		"#ff000000", // 11 Shadow
		toArgb(accent), // 12 Highlight
		toArgb(s.foreground), // 13 HighlightedText
		toArgb(accent), // 14 Link
		toArgb(c.color5), // 15 LinkVisited
		toArgb(altBase), // 16 AlternateBase
		toArgb(c.color0), // 17 ToolTipBase
		toArgb(s.foreground), // 18 ToolTipText
		toArgbAlpha(c.color8, "80"), // 19 PlaceholderText
		toArgb(accent), // 20 Accent
		toArgb(s.foreground), // 21 padding
	].join(", ");

	// Inactive: dimmed highlight, dimmed text for WindowText
	const inactiveLine = [
		toArgbAlpha(s.foreground, "bf"), // 0  WindowText (dimmed)
		toArgb(buttonBg), // 1  Button
		toArgb(light), // 2  Light
		toArgb(midlight), // 3  Midlight
		toArgb(dark), // 4  Dark
		toArgb(c.color8), // 5  Mid
		toArgbAlpha(s.foreground, "bf"), // 6  Text (dimmed)
		toArgb(s.foreground), // 7  BrightText
		toArgbAlpha(s.foreground, "bf"), // 8  ButtonText (dimmed)
		toArgb(s.background), // 9  Base
		toArgb(s.background), // 10 Window
		"#ff000000", // 11 Shadow
		toArgb(adjustLightness(accent, -30)), // 12 Highlight (dimmed)
		toArgbAlpha(s.foreground, "bf"), // 13 HighlightedText
		toArgb(accent), // 14 Link
		toArgb(c.color5), // 15 LinkVisited
		toArgb(altBase), // 16 AlternateBase
		toArgb(c.color0), // 17 ToolTipBase
		toArgb(s.foreground), // 18 ToolTipText
		toArgbAlpha(c.color8, "80"), // 19 PlaceholderText
		toArgb(adjustLightness(accent, -30)), // 20 Accent (dimmed)
		toArgb(s.foreground), // 21 padding
	].join(", ");

	// Disabled: even more dimmed
	const disabledLine = [
		toArgbAlpha(s.foreground, "80"), // 0  WindowText
		toArgb(adjustLightness(buttonBg, -10)), // 1  Button
		toArgb(light), // 2  Light
		toArgb(midlight), // 3  Midlight
		toArgb(dark), // 4  Dark
		toArgb(c.color8), // 5  Mid
		toArgbAlpha(s.foreground, "80"), // 6  Text
		toArgb(s.foreground), // 7  BrightText
		toArgbAlpha(s.foreground, "80"), // 8  ButtonText
		toArgb(s.background), // 9  Base
		toArgb(s.background), // 10 Window
		"#ff000000", // 11 Shadow
		toArgb(adjustLightness(s.background, 10)), // 12 Highlight (nearly invisible)
		toArgbAlpha(s.foreground, "80"), // 13 HighlightedText
		toArgb(adjustLightness(accent, -40)), // 14 Link
		toArgb(adjustLightness(c.color5, -40)), // 15 LinkVisited
		toArgb(altBase), // 16 AlternateBase
		toArgb(c.color0), // 17 ToolTipBase
		toArgb(s.foreground), // 18 ToolTipText
		toArgbAlpha(c.color8, "80"), // 19 PlaceholderText
		toArgb(adjustLightness(s.background, 10)), // 20 Accent
		toArgb(s.foreground), // 21 padding
	].join(", ");

	const colorScheme = `[ColorScheme]
active_colors=${activeLine}
inactive_colors=${inactiveLine}
disabled_colors=${disabledLine}
`;

	// Ensure qt6ct colors directory exists
	const colorsDir = `${GLib.get_user_config_dir()}/qt6ct/colors`;
	const colorsDirFile = Gio.File.new_for_path(colorsDir);
	if (!colorsDirFile.query_exists(null)) {
		colorsDirFile.make_directory_with_parents(null);
	}

	const schemePath = `${colorsDir}/pywal.conf`;
	await writeFileAsync(schemePath, colorScheme).catch((e: Error) => {
		console.error(
			`ColorUtils: Failed to write qt6ct color scheme: ${e.message}`,
		);
	});

	// Update qt6ct.conf to point to our color scheme
	const qt6ctConfPath = `${GLib.get_user_config_dir()}/qt6ct/qt6ct.conf`;
	const qt6ctConfFile = Gio.File.new_for_path(qt6ctConfPath);
	if (qt6ctConfFile.query_exists(null)) {
		try {
			const [ok, contents] = qt6ctConfFile.load_contents(null);
			if (ok) {
				let conf = new TextDecoder().decode(contents);
				conf = conf.replace(
					/^color_scheme_path=.*$/m,
					`color_scheme_path=${schemePath}`,
				);
				if (!conf.includes("custom_palette=true")) {
					conf = conf.replace(
						/^\[Appearance\]$/m,
						"[Appearance]\ncustom_palette=true",
					);
				}
				await writeFileAsync(qt6ctConfPath, conf);
			}
		} catch (e) {
			console.error(`ColorUtils: Failed to update qt6ct.conf: ${e}`);
		}
	}
}

export async function updateTelegramTheme(data: ColorData): Promise<void> {
	const c = data.colors;
	const s = data.special;
	const accent = data.accent || c.color4;
	const surface0 = adjustLightness(s.background, 15);
	const surface1 = adjustLightness(s.background, 25);
	const surface2 = adjustLightness(s.background, 40);
	const mantle = adjustLightness(s.background, -5);
	const crust = adjustLightness(s.background, -10);
	const overlay0 = adjustLightness(s.foreground, -80);
	const overlay1 = adjustLightness(s.foreground, -65);
	const overlay2 = adjustLightness(s.foreground, -50);
	const subtext0 = adjustLightness(s.foreground, -30);
	const subtext1 = adjustLightness(s.foreground, -15);

	const theme = `// Generated by novashell

windowBg: ${s.background};
windowFg: ${s.foreground};
windowBgOver: ${surface1};
windowBgRipple: ${surface1};
windowBoldFg: ${s.foreground};
windowBoldFgOver: ${s.foreground};
windowFgOver: ${s.foreground};
windowSubTextFg: ${subtext0};
windowSubTextFgOver: ${subtext1};
windowBgActive: ${overlay2};
windowFgActive: ${s.foreground};
windowActiveTextFg: ${s.foreground};
windowShadowFg: ${s.background};
windowShadowFgFallback: ${s.background};
shadowFg: ${crust}11;
slideFadeOutBg: #0000003c;
slideFadeOutShadowFg: ${c.color0}20;
imageBg: ${s.background};
imageBgTransparent: ${s.background};
activeButtonBg: ${accent};
activeButtonBgOver: ${accent};
activeButtonBgRipple: ${accent};
activeButtonFg: ${crust};
activeButtonFgOver: ${crust};
activeButtonSecondaryFg: ${mantle};
activeButtonSecondaryFgOver: ${mantle};
activeLineFg: ${overlay2};
activeLineFgError: ${c.color1};
lightButtonBg: ${surface0};
lightButtonBgOver: ${surface0};
lightButtonBgRipple: ${surface1};
lightButtonFg: ${accent};
lightButtonFgOver: ${accent};
attentionButtonFg: ${s.foreground};
attentionButtonFgOver: ${s.foreground};
attentionButtonBgOver: ${surface1}cc;
attentionButtonBgRipple: ${surface1};
outlineButtonBg: ${s.background};
outlineButtonBgOver: ${surface0};
outlineButtonOutlineFg: ${accent};
outlineButtonBgRipple: ${surface1};
menuBg: ${s.background};
menuBgOver: ${surface0};
menuBgRipple: ${surface1};
menuIconFg: ${s.foreground};
menuIconFgOver: ${subtext0};
menuSubmenuArrowFg: ${s.foreground};
menuFgDisabled: ${subtext0};
menuSeparatorFg: ${surface0};
scrollBg: ${surface2}cc;
scrollBgOver: ${surface2}cc;
scrollBarBg: ${overlay1}cc;
scrollBarBgOver: ${surface2}cc;
smallCloseIconFg: ${s.foreground};
smallCloseIconFgOver: ${s.foreground};
radialFg: ${s.foreground};
radialBg: ${s.background};
placeholderFg: ${subtext0};
placeholderFgActive: ${subtext1};
inputBorderFg: ${subtext0};
filterInputBorderFg: ${accent};
filterInputInactiveBg: ${surface0};
checkboxFg: ${subtext0};
sliderBgInactive: ${surface0};
sliderBgActive: ${surface1};
tooltipBg: ${s.background};
tooltipFg: ${s.foreground};
tooltipBorderFg: ${surface0};
titleBg: ${s.background};
titleShadow: #00000003;
titleButtonFg: ${s.foreground};
titleButtonBgOver: ${surface0};
titleButtonFgOver: ${s.foreground};
titleButtonCloseFg: ${s.foreground};
titleButtonCloseBgOver: ${c.color1};
titleButtonCloseFgOver: ${s.foreground};
titleFg: ${s.foreground};
titleFgActive: ${s.foreground};
trayCounterBg: ${c.color1};
trayCounterBgMute: ${c.color8};
trayCounterFg: ${s.foreground};
trayCounterBgMacInactive: ${c.color8};
trayCounterFgMacInactive: ${s.foreground};
layerBg: #0000007f;
cancelIconFg: ${s.foreground};
cancelIconFgOver: ${s.foreground};
boxBg: ${s.background};
boxTextFg: ${s.foreground};
boxTextFgGood: ${s.foreground};
boxTextFgError: ${c.color1};
boxTitleFg: ${s.foreground};
boxSearchBg: ${s.background};
boxTitleAdditionalFg: ${subtext0};
boxTitleCloseFg: ${s.foreground};
boxTitleCloseFgOver: ${s.foreground};
membersAboutLimitFg: ${subtext0};
contactsBg: ${s.background};
contactsBgOver: ${surface0};
contactsNameFg: ${s.foreground};
contactsStatusFg: ${s.foreground};
contactsStatusFgOver: ${overlay0};
contactsStatusFgOnline: ${subtext0};
photoCropFadeBg: ${s.background}b0;
photoCropPointFg: ${s.foreground}c0;
introBg: ${s.background};
introTitleFg: ${s.foreground};
introDescriptionFg: ${subtext0};
introCoverTopBg: ${s.background};
introCoverBottomBg: ${s.background};
introCoverIconsFg: ${subtext0};
introCoverPlaneTrace: ${c.color8}40;
introCoverPlaneInner: ${surface1};
introCoverPlaneOuter: ${surface0};
introCoverPlaneTop: ${s.foreground};
dialogsBg: ${s.background};
dialogsNameFg: ${s.foreground};
dialogsChatIconFg: ${s.foreground};
dialogsDateFg: ${subtext0};
dialogsTextFg: ${subtext0};
dialogsTextFgService: ${accent};
dialogsDraftFg: ${c.color1};
dialogsVerifiedIconBg: ${accent};
dialogsVerifiedIconFg: ${s.background};
dialogsSendingIconFg: ${subtext0};
dialogsSentIconFg: ${accent};
dialogsUnreadBg: ${accent};
dialogsUnreadBgMuted: ${c.color8};
dialogsUnreadFg: ${s.background};
dialogsBgOver: ${surface0};
dialogsBgActive: ${surface1};
dialogsNameFgActive: ${s.foreground};
dialogsChatIconFgActive: ${s.foreground};
dialogsDateFgActive: ${subtext0};
dialogsTextFgActive: ${subtext0};
dialogsTextFgServiceActive: ${accent};
dialogsDraftFgActive: ${c.color1};
dialogsOnlineBadgeFg: ${c.color2};
dialogsForwardBg: ${accent};
dialogsForwardFg: ${s.background};
searchedBarBg: ${surface0};
searchedBarFg: ${s.foreground};
topBarBg: ${s.background};
emojiPanBg: ${s.background};
emojiPanCategories: ${s.background};
emojiPanHeaderFg: ${subtext0};
emojiPanHeaderBg: ${s.background};
stickerPanDeleteBg: ${c.color8}cc;
stickerPanDeleteFg: ${s.foreground};
stickerPreviewBg: ${s.background}b0;
historyTextInFg: ${s.foreground};
historyTextInFgSelected: ${s.foreground};
historyTextOutFg: ${s.foreground};
historyTextOutFgSelected: ${s.foreground};
historyLinkInFg: ${accent};
historyLinkInFgSelected: ${accent};
historyLinkOutFg: ${accent};
historyLinkOutFgSelected: ${accent};
historyFileNameInFg: ${s.foreground};
historyFileNameInFgSelected: ${s.foreground};
historyFileNameOutFg: ${s.foreground};
historyFileNameOutFgSelected: ${s.foreground};
historyOutIconFg: ${accent};
historyOutIconFgSelected: ${accent};
historyIconFgInverted: ${s.background};
historySendingOutIconFg: ${accent};
historySendingInIconFg: ${accent};
historySendingInvertedIconFg: ${s.foreground};
historyCallArrowInFg: ${c.color2};
historyCallArrowInFgSelected: ${c.color2};
historyCallArrowMissedInFg: ${c.color1};
historyCallArrowMissedInFgSelected: ${c.color1};
historyCallArrowOutFg: ${c.color2};
historyCallArrowOutFgSelected: ${c.color2};
historyUnreadBarBg: ${surface0};
historyUnreadBarBorder: ${surface0};
historyUnreadBarFg: ${s.foreground};
historyForwardChooseBg: ${accent};
historyForwardChooseFg: ${s.background};
historyPeer1NameFg: ${c.color1};
historyPeer1NameFgSelected: ${c.color1};
historyPeer1UserpicBg: ${c.color1};
historyPeer2NameFg: ${c.color2};
historyPeer2NameFgSelected: ${c.color2};
historyPeer2UserpicBg: ${c.color2};
historyPeer3NameFg: ${c.color3};
historyPeer3NameFgSelected: ${c.color3};
historyPeer3UserpicBg: ${c.color3};
historyPeer4NameFg: ${c.color4};
historyPeer4NameFgSelected: ${c.color4};
historyPeer4UserpicBg: ${c.color4};
historyPeer5NameFg: ${c.color5};
historyPeer5NameFgSelected: ${c.color5};
historyPeer5UserpicBg: ${c.color5};
historyPeer6NameFg: ${c.color6};
historyPeer6NameFgSelected: ${c.color6};
historyPeer6UserpicBg: ${c.color6};
historyPeer7NameFg: ${adjustLightness(c.color4, 30)};
historyPeer7NameFgSelected: ${adjustLightness(c.color4, 30)};
historyPeer7UserpicBg: ${adjustLightness(c.color4, 30)};
historyPeer8NameFg: ${adjustLightness(c.color1, 30)};
historyPeer8NameFgSelected: ${adjustLightness(c.color1, 30)};
historyPeer8UserpicBg: ${adjustLightness(c.color1, 30)};
historyPeerUserpicFg: ${s.background};
historyScrollBarBg: ${overlay1}cc;
historyScrollBarBgOver: ${surface2}cc;
historyScrollBg: ${surface2}cc;
historyScrollBgOver: ${surface2}cc;
historyComposeButtonBg: ${s.background};
historyComposeButtonBgOver: ${surface0};
historyComposeButtonBgRipple: ${surface1};
historyComposeIconFg: ${subtext0};
historyComposeIconFgOver: ${s.foreground};
historyComposeAreaBg: ${s.background};
historyComposeAreaFg: ${s.foreground};
historyComposeAreaFgService: ${accent};
historyComposeIconFgInactive: ${c.color8};
historyComposeIconFgActive: ${accent};
historySendIconFg: ${accent};
historySendIconFgOver: ${accent};
historyPinnedBg: ${surface0};
historyReplyBg: ${surface0};
historyReplyCancelFg: ${s.foreground};
historyReplyCancelFgOver: ${s.foreground};
historyToDownBg: ${s.background};
historyToDownBgOver: ${surface0};
historyToDownBgRipple: ${surface1};
historyToDownFg: ${subtext0};
historyToDownFgOver: ${s.foreground};
historyToDownShadow: #00000040;
msgInBg: ${surface0};
msgInBgSelected: ${surface1};
msgOutBg: ${adjustLightness(accent, -60)};
msgOutBgSelected: ${adjustLightness(accent, -45)};
msgSelectOverlay: ${accent}40;
msgStickerOverlay: ${accent}40;
msgInServiceFg: ${accent};
msgInServiceFgSelected: ${accent};
msgOutServiceFg: ${accent};
msgOutServiceFgSelected: ${accent};
msgInShadow: #00000020;
msgInShadowSelected: #00000030;
msgOutShadow: #00000020;
msgOutShadowSelected: #00000030;
msgInDateFg: ${subtext0};
msgInDateFgSelected: ${subtext0};
msgOutDateFg: ${subtext0};
msgOutDateFgSelected: ${subtext0};
msgServiceFg: ${s.foreground};
msgServiceBg: ${surface0};
msgServiceBgSelected: ${surface1};
msgInReplyBarColor: ${accent};
msgInReplyBarSelColor: ${accent};
msgOutReplyBarColor: ${accent};
msgOutReplyBarSelColor: ${accent};
msgImgReplyBarColor: ${accent};
msgInMonoFg: ${c.color2};
msgOutMonoFg: ${c.color2};
msgInMonoFgSelected: ${c.color2};
msgOutMonoFgSelected: ${c.color2};
msgDateImgFg: ${s.foreground};
msgDateImgBg: ${s.background}b0;
msgDateImgBgOver: ${s.background}c0;
msgDateImgBgSelected: ${s.background}d0;
msgFileThumbLinkInFg: ${accent};
msgFileThumbLinkInFgSelected: ${accent};
msgFileThumbLinkOutFg: ${accent};
msgFileThumbLinkOutFgSelected: ${accent};
msgFileInBg: ${accent};
msgFileInBgOver: ${accent};
msgFileInBgSelected: ${accent};
msgFileOutBg: ${accent};
msgFileOutBgOver: ${accent};
msgFileOutBgSelected: ${accent};
msgFile1Bg: ${c.color4};
msgFile1BgDark: ${adjustLightness(c.color4, -30)};
msgFile1BgOver: ${adjustLightness(c.color4, 15)};
msgFile1BgSelected: ${adjustLightness(c.color4, 15)};
msgFile2Bg: ${c.color2};
msgFile2BgDark: ${adjustLightness(c.color2, -30)};
msgFile2BgOver: ${adjustLightness(c.color2, 15)};
msgFile2BgSelected: ${adjustLightness(c.color2, 15)};
msgFile3Bg: ${c.color1};
msgFile3BgDark: ${adjustLightness(c.color1, -30)};
msgFile3BgOver: ${adjustLightness(c.color1, 15)};
msgFile3BgSelected: ${adjustLightness(c.color1, 15)};
msgFile4Bg: ${c.color3};
msgFile4BgDark: ${adjustLightness(c.color3, -30)};
msgFile4BgOver: ${adjustLightness(c.color3, 15)};
msgFile4BgSelected: ${adjustLightness(c.color3, 15)};
msgWaveformInActive: ${accent};
msgWaveformInActiveSelected: ${accent};
msgWaveformInInactive: ${c.color8};
msgWaveformInInactiveSelected: ${c.color8};
msgWaveformOutActive: ${accent};
msgWaveformOutActiveSelected: ${accent};
msgWaveformOutInactive: ${c.color8};
msgWaveformOutInactiveSelected: ${c.color8};
msgBotKbOverBgAdd: ${surface0}40;
msgBotKbIconFg: ${s.foreground};
msgBotKbRippleBg: ${surface0}30;
mediaInFg: ${subtext0};
mediaInFgSelected: ${subtext0};
mediaOutFg: ${subtext0};
mediaOutFgSelected: ${subtext0};
youtubePlayIconBg: ${c.color1}e8;
youtubePlayIconFg: ${s.foreground};
videoPlayIconBg: ${s.background}b0;
videoPlayIconFg: ${s.foreground};
toastBg: ${crust}cc;
toastFg: ${s.foreground};
reportSpamBg: ${surface0};
reportSpamFg: ${c.color1};
historyToDownBadgeBg: ${accent};
historyToDownBadgeFg: ${s.background};
profileStatusFg: ${subtext0};
profileVerifiedCheckBg: ${accent};
profileVerifiedCheckFg: ${s.background};
profileAdminStartFg: ${accent};
callArrowFg: ${c.color4};
callArrowMissedFg: ${c.color1};
callAnswerBg: ${c.color2};
callAnswerRipple: ${c.color2};
callAnswerBgOuter: ${c.color2};
callHangupBg: ${c.color1};
callHangupRipple: ${c.color5};
callCancelBg: ${c.color1};
callCancelFg: ${crust};
callCancelRipple: ${c.color5};
callMuteRipple: ${c.color1};
callBarBg: ${c.color2};
callBarFg: ${crust};
callBarMuteRipple: ${c.color2};
callBarBgMuted: ${c.color1};
callBarUnmuteRipple: ${c.color1};
callBg: ${s.background}cc;
callBgButton: ${mantle}cc;
callBgOpaque: ${mantle};
callIconFg: ${crust};
callIconBg: ${c.color2};
callIconActiveRipple: ${c.color4};
callIconBgActive: ${c.color4};
callIconFgActive: ${crust};
callFingerprintBg: ${crust}cc;
callNameFg: ${s.foreground};
callStatusFg: ${subtext0};
changePhoneSimcardFrom: ${c.color3};
changePhoneSimcardTo: ${c.color3};
botKbBg: ${surface0};
botKbDownBg: ${surface1};
dialogsChatIconFgOver: ${s.foreground};
dialogsDateFgOver: ${subtext0};
dialogsDraftFgOver: ${c.color1};
dialogsMenuIconFg: ${s.foreground};
dialogsMenuIconFgOver: ${s.foreground};
dialogsNameFgOver: ${s.foreground};
dialogsOnlineBadgeFgActive: ${c.color2};
dialogsRippleBg: ${surface1};
dialogsRippleBgActive: ${surface1};
dialogsSendingIconFgActive: ${subtext0};
dialogsSendingIconFgOver: ${subtext0};
dialogsSentIconFgActive: ${accent};
dialogsSentIconFgOver: ${accent};
dialogsTextFgOver: ${subtext0};
dialogsTextFgServiceOver: ${accent};
dialogsUnreadBgActive: ${accent};
dialogsUnreadBgMutedActive: ${c.color8};
dialogsUnreadBgMutedOver: ${c.color8};
dialogsUnreadBgOver: ${accent};
dialogsUnreadFgActive: ${s.background};
dialogsUnreadFgOver: ${s.background};
dialogsVerifiedIconBgActive: ${accent};
dialogsVerifiedIconBgOver: ${accent};
dialogsVerifiedIconFgActive: ${s.background};
dialogsVerifiedIconFgOver: ${s.background};
emojiIconFg: ${subtext0};
emojiIconFgActive: ${accent};
filterInputActiveBg: ${s.background};
mainMenuBg: ${s.background};
mainMenuCloudBg: ${mantle};
mainMenuCloudFg: ${s.foreground};
mainMenuCoverBg: ${mantle};
mainMenuCoverFg: ${s.foreground};
mediaPlayerActiveFg: ${accent};
mediaPlayerBg: ${s.background};
mediaPlayerDisabledFg: ${subtext0};
mediaPlayerInactiveFg: ${c.color8};
mediaviewBg: ${s.background};
mediaviewCaptionBg: ${s.background}cc;
mediaviewCaptionFg: ${s.foreground};
mediaviewControlBg: ${s.background}cc;
mediaviewControlFg: ${s.foreground};
mediaviewFileBg: ${surface0};
mediaviewFileBlueCornerFg: ${c.color4};
mediaviewFileExtFg: ${s.foreground};
mediaviewFileGreenCornerFg: ${c.color2};
mediaviewFileNameFg: ${s.foreground};
mediaviewFileRedCornerFg: ${c.color1};
mediaviewFileSizeFg: ${subtext0};
mediaviewFileYellowCornerFg: ${c.color3};
mediaviewMenuBg: ${s.background};
mediaviewMenuBgOver: ${surface0};
mediaviewMenuBgRipple: ${surface1};
mediaviewMenuFg: ${s.foreground};
mediaviewPlaybackActive: ${accent};
mediaviewPlaybackActiveOver: ${accent};
mediaviewPlaybackIconFg: ${s.foreground};
mediaviewPlaybackIconFgOver: ${s.foreground};
mediaviewPlaybackInactive: ${c.color8};
mediaviewPlaybackInactiveOver: ${c.color8};
mediaviewPlaybackProgressFg: ${s.foreground}20;
mediaviewSaveMsgBg: ${mantle}cc;
mediaviewSaveMsgFg: ${s.foreground};
mediaviewTextLinkFg: ${accent};
mediaviewTransparentBg: ${s.background};
mediaviewTransparentFg: ${s.foreground};
mediaviewVideoBg: ${s.background};
notificationBg: ${mantle};
notificationSampleCloseFg: ${subtext0};
notificationSampleNameFg: ${s.foreground};
notificationSampleTextFg: ${subtext0};
notificationSampleUserpicFg: ${accent};
notificationsBoxMonitorFg: ${s.foreground};
notificationsBoxScreenBg: ${surface0};
overviewCheckBg: ${accent}40;
overviewCheckBorder: ${accent};
overviewCheckFg: ${s.foreground};
overviewCheckFgActive: ${s.background};
overviewPhotoSelectOverlay: ${accent}40;
profileStatusFgOver: ${subtext0};
sideBarBadgeBg: ${accent};
sideBarBadgeBgMuted: ${c.color8};
sideBarBg: ${mantle};
sideBarBgActive: ${surface0};
sideBarBgRipple: ${surface1};
sideBarIconFg: ${subtext0};
sideBarIconFgActive: ${accent};
sideBarTextFg: ${s.foreground};
sideBarTextFgActive: ${accent};
statisticsChartActive: ${accent};
statisticsChartInactive: ${c.color8};
titleBgActive: ${s.background};
titleButtonBg: ${s.background}00;
titleButtonBgActive: ${s.background}00;
titleButtonBgActiveOver: ${surface0};
titleButtonCloseBg: ${s.background}00;
titleButtonCloseBgActive: ${s.background}00;
titleButtonCloseBgActiveOver: ${c.color1};
titleButtonCloseFgActive: ${s.foreground};
titleButtonCloseFgActiveOver: ${s.foreground};
titleButtonFgActive: ${s.foreground};
titleButtonFgActiveOver: ${s.foreground};
importantTooltipBg: ${mantle};
importantTooltipFg: ${s.foreground};
importantTooltipFgLink: ${accent};
introErrorFg: ${c.color1};
groupCallBg: ${s.background}cc;
groupCallActiveFg: ${c.color2};
groupCallIconFg: ${s.foreground};
groupCallLeaveBg: ${c.color1};
groupCallLeaveBgRipple: ${adjustLightness(c.color1, -15)};
groupCallMemberActiveIcon: ${c.color2};
groupCallMemberActiveStatus: ${c.color2};
groupCallMemberInactiveIcon: ${subtext0};
groupCallMemberInactiveStatus: ${subtext0};
groupCallMemberMutedIcon: ${c.color1};
groupCallMemberNotJoinedStatus: ${c.color8};
groupCallMembersBg: ${s.background};
groupCallMembersBgOver: ${surface0};
groupCallMembersBgRipple: ${surface1};
groupCallMembersFg: ${s.foreground};
groupCallMenuBg: ${mantle};
groupCallMenuBgOver: ${surface0};
groupCallMenuBgRipple: ${surface1};
groupCallMuted1: ${c.color1};
groupCallMuted2: ${adjustLightness(c.color1, -20)};
groupCallVideoSubTextFg: ${subtext0};
groupCallVideoTextFg: ${s.foreground};
groupCallLive1: ${c.color2};
groupCallLive2: ${adjustLightness(c.color2, -20)};
groupCallForceMuted1: ${c.color1};
groupCallForceMuted2: ${adjustLightness(c.color1, -15)};
groupCallForceMuted3: ${adjustLightness(c.color1, -30)};
groupCallForceMutedBar1: ${c.color1};
groupCallForceMutedBar2: ${adjustLightness(c.color1, -15)};
groupCallForceMutedBar3: ${adjustLightness(c.color1, -30)};
historyFileInIconFg: ${s.background};
historyFileInIconFgSelected: ${s.background};
historyFileInRadialFg: ${s.background};
historyFileInRadialFgSelected: ${s.background};
historyFileOutIconFg: ${s.background};
historyFileOutIconFgSelected: ${s.background};
historyFileOutRadialFg: ${s.background};
historyFileOutRadialFgSelected: ${s.background};
historyFileThumbIconFg: ${s.foreground};
historyFileThumbIconFgSelected: ${s.foreground};
historyFileThumbRadialFg: ${s.foreground};
historyFileThumbRadialFgSelected: ${s.foreground};
historyPeer1UserpicBg2: ${adjustLightness(c.color1, 20)};
historyPeer2UserpicBg2: ${adjustLightness(c.color2, 20)};
historyPeer3UserpicBg2: ${adjustLightness(c.color3, 20)};
historyPeer4UserpicBg2: ${adjustLightness(c.color4, 20)};
historyPeer5UserpicBg2: ${adjustLightness(c.color5, 20)};
historyPeer6UserpicBg2: ${adjustLightness(c.color6, 20)};
historyPeer7UserpicBg2: ${adjustLightness(c.color4, 50)};
historyPeer8UserpicBg2: ${adjustLightness(c.color1, 50)};
historyPeerSavedMessagesBg: ${accent};
historyPeerSavedMessagesBg2: ${adjustLightness(accent, 20)};
historyReplyIconFg: ${accent};
historyVideoMessageProgressFg: ${accent};
`;

	const cacheDir = `${GLib.get_user_cache_dir()}/novashell`;
	const cacheDirFile = Gio.File.new_for_path(cacheDir);
	if (!cacheDirFile.query_exists(null)) {
		cacheDirFile.make_directory_with_parents(null);
	}

	await writeFileAsync(`${cacheDir}/telegram-theme.tdesktop-theme`, theme).catch((e: Error) => {
		console.error(`ColorUtils: Failed to write Telegram theme: ${e.message}`);
	});
}

export async function updateVesktopTheme(data: ColorData): Promise<void> {
	const c = data.colors;
	const s = data.special;
	const accent = data.accent || c.color4;
	const mantle = adjustLightness(s.background, -5);
	const crust = adjustLightness(s.background, -10);
	const surface0 = adjustLightness(s.background, 15);
	const surface1 = adjustLightness(s.background, 25);
	const surface2 = adjustLightness(s.background, 40);
	const overlay0 = adjustLightness(s.foreground, -80);
	const overlay2 = adjustLightness(s.foreground, -50);
	const subtext0 = adjustLightness(s.foreground, -30);
	const subtext1 = adjustLightness(s.foreground, -15);

	const baseLow = adjustLightness(s.background, -3);
	const channelDefault = adjustLightness(subtext0, -5);
	const sky = adjustLightness(c.color6, 15);

	const vars = `
  --background-primary: ${s.background} !important;
  --background-secondary: ${mantle} !important;
  --background-secondary-alt: ${baseLow} !important;
  --background-tertiary: ${crust} !important;
  --background-floating: ${mantle} !important;
  --background-modifier-hover: ${overlay2}15 !important;
  --background-modifier-active: ${overlay2}25 !important;
  --background-modifier-selected: ${overlay0}30 !important;
  --background-modifier-accent: ${surface2}30 !important;
  --background-accent: ${surface1} !important;
  --background-message-hover: ${crust}30 !important;
  --channeltextarea-background: ${mantle} !important;
  --background-base-lowest: ${crust} !important;
  --background-base-lower: ${mantle} !important;
  --background-base-low: ${baseLow} !important;
  --bg-surface-raised: ${mantle} !important;
  --background-surface-highest: ${surface0} !important;
  --background-surface-higher: ${adjustLightness(surface0, -3)} !important;
  --background-surface-high: ${s.background} !important;
  --background-gradient-highest: ${baseLow} !important;
  --home-background: ${s.background} !important;
  --app-frame-background: ${adjustLightness(crust, -2)} !important;
  --chat-background: ${s.background} !important;
  --chat-background-default: ${s.background} !important;
  --chat-border: ${crust} !important;
  --chat-text-muted: ${subtext0} !important;
  --text-default: ${s.foreground} !important;
  --text-normal: ${s.foreground} !important;
  --text-muted: ${subtext0} !important;
  --text-link: ${accent} !important;
  --text-positive: ${c.color2} !important;
  --text-warning: ${c.color3} !important;
  --text-danger: ${c.color1} !important;
  --text-brand: ${accent} !important;
  --text-strong: ${s.foreground} !important;
  --text-subtle: ${subtext1} !important;
  --interactive-normal: ${subtext1} !important;
  --interactive-hover: ${s.foreground} !important;
  --interactive-active: ${s.foreground} !important;
  --interactive-muted: ${overlay0} !important;
  --interactive-icon-default: ${s.foreground} !important;
  --interactive-icon-hover: ${s.foreground} !important;
  --interactive-icon-active: ${s.foreground} !important;
  --interactive-text-default: ${s.foreground} !important;
  --interactive-text-hover: ${s.foreground} !important;
  --interactive-text-active: ${s.foreground} !important;
  --interactive-background-hover: ${overlay2}15 !important;
  --interactive-background-selected: ${overlay0}20 !important;
  --interactive-background-active: ${s.foreground}17 !important;
  --header-primary: ${s.foreground} !important;
  --header-secondary: ${subtext0} !important;
  --brand-100: ${adjustLightness(accent, 90)} !important;
  --brand-130: ${adjustLightness(accent, 80)} !important;
  --brand-160: ${adjustLightness(accent, 70)} !important;
  --brand-200: ${adjustLightness(accent, 60)} !important;
  --brand-230: ${adjustLightness(accent, 50)} !important;
  --brand-260: ${adjustLightness(accent, 40)} !important;
  --brand-300: ${adjustLightness(accent, 30)} !important;
  --brand-330: ${adjustLightness(accent, 20)} !important;
  --brand-360: ${adjustLightness(accent, 15)} !important;
  --brand-400: ${adjustLightness(accent, 10)} !important;
  --brand-430: ${adjustLightness(accent, 5)} !important;
  --brand-460: ${adjustLightness(accent, 2)} !important;
  --brand-500: ${accent} !important;
  --brand-530: ${adjustLightness(accent, -5)} !important;
  --brand-560: ${adjustLightness(accent, -10)} !important;
  --brand-600: ${adjustLightness(accent, -15)} !important;
  --brand-630: ${adjustLightness(accent, -20)} !important;
  --brand-660: ${adjustLightness(accent, -25)} !important;
  --brand-700: ${adjustLightness(accent, -30)} !important;
  --brand-730: ${adjustLightness(accent, -35)} !important;
  --brand-760: ${adjustLightness(accent, -40)} !important;
  --brand-800: ${adjustLightness(accent, -45)} !important;
  --brand-830: ${adjustLightness(accent, -50)} !important;
  --brand-860: ${adjustLightness(accent, -55)} !important;
  --brand-900: ${adjustLightness(accent, -60)} !important;
  --brand-experiment: ${accent} !important;
  --brand-experiment-560: ${adjustLightness(accent, -10)} !important;
  --brand-experiment-600: ${adjustLightness(accent, -15)} !important;
  --blurple-50: ${accent} !important;
  --blurple-60: ${adjustLightness(accent, -10)} !important;
  --channels-default: ${channelDefault} !important;
  --channel-icon: ${channelDefault} !important;
  --channel-text-area-placeholder: ${s.foreground}80 !important;
  --icon-muted: ${channelDefault} !important;
  --icon-default: ${s.foreground} !important;
  --icon-strong: ${s.foreground} !important;
  --icon-subtle: ${subtext1} !important;
  --icon-voice-muted: ${c.color1} !important;
  --border-muted: ${surface0} !important;
  --border-strong: ${mantle} !important;
  --border-normal: ${crust} !important;
  --border-subtle: ${s.background} !important;
  --background-mod-muted: ${surface2}0d !important;
  --background-mod-normal: ${surface2}26 !important;
  --background-mod-subtle: ${surface2}40 !important;
  --background-mod-strong: ${surface2}73 !important;
  --background-code: ${s.background} !important;
  --input-background: ${crust} !important;
  --input-background-default: ${crust} !important;
  --input-text-default: ${s.foreground} !important;
  --input-placeholder-text: ${subtext0} !important;
  --input-placeholder-text-default: ${subtext1} !important;
  --input-border-default: ${overlay0} !important;
  --checkbox-icon-active: ${crust} !important;
  --checkbox-border-default: ${overlay0} !important;
  --radio-thumb-background-active: ${crust} !important;
  --textbox-markdown-syntax: ${overlay0} !important;
  --spoiler-revealed-background: ${surface0} !important;
  --spoiler-hidden-background: ${surface2} !important;
  --scrollbar-thin-thumb: ${accent} !important;
  --scrollbar-thin-track: transparent !important;
  --scrollbar-auto-thumb: ${accent} !important;
  --scrollbar-auto-track: ${crust} !important;
  --scrollbar-auto-scrollbar-color-thumb: ${accent} !important;
  --scrollbar-auto-scrollbar-color-track: ${crust} !important;
  --control-brand-foreground: ${accent} !important;
  --control-brand-foreground-new: ${accent} !important;
  --control-primary-background-default: ${accent} !important;
  --control-primary-background-hover: ${adjustLightness(accent, -8)} !important;
  --control-primary-background-active: ${adjustLightness(accent, -13)} !important;
  --control-secondary-background-default: ${surface1} !important;
  --control-secondary-background-hover: ${adjustLightness(surface1, -5)} !important;
  --control-secondary-background-active: ${adjustLightness(surface1, -8)} !important;
  --control-secondary-border-default: ${surface0} !important;
  --control-secondary-text-default: ${s.foreground} !important;
  --control-secondary-text-hover: ${s.foreground} !important;
  --control-critical-primary-background-default: ${c.color1} !important;
  --control-critical-primary-background-hover: ${adjustLightness(c.color1, -5)} !important;
  --control-critical-primary-text-default: ${s.background} !important;
  --control-connected-background-default: ${c.color2} !important;
  --button-outline-primary-text: ${s.foreground} !important;
  --button-outline-brand-text: ${s.foreground} !important;
  --mention-foreground: ${accent} !important;
  --mention-background: ${accent}30 !important;
  --message-reacted-background-default: ${accent}30 !important;
  --message-reacted-text-default: ${accent} !important;
  --message-mentioned-background-default: ${c.color3}10 !important;
  --message-mentioned-background-hover: ${c.color3}08 !important;
  --message-highlight-background-default: ${accent}0d !important;
  --message-highlight-background-hover: ${accent}0a !important;
  --status-positive: ${c.color2} !important;
  --status-positive-background: ${c.color2} !important;
  --status-positive-text: ${s.background} !important;
  --status-warning: ${c.color3} !important;
  --status-warning-background: ${c.color3} !important;
  --status-warning-text: ${s.background} !important;
  --status-danger: ${c.color1} !important;
  --text-status-online: ${c.color2} !important;
  --text-status-idle: ${c.color3} !important;
  --text-status-dnd: ${c.color1} !important;
  --text-status-offline: ${subtext1} !important;
  --icon-status-online: ${c.color2} !important;
  --icon-status-idle: ${c.color3} !important;
  --icon-status-dnd: ${c.color1} !important;
  --icon-status-offline: ${subtext1} !important;
  --text-feedback-positive: ${c.color2} !important;
  --text-feedback-critical: ${c.color1} !important;
  --text-feedback-warning: ${c.color3} !important;
  --text-feedback-info: ${c.color4} !important;
  --background-feedback-positive: ${c.color2}15 !important;
  --background-feedback-critical: ${c.color1}15 !important;
  --background-feedback-warning: ${c.color3}15 !important;
  --background-feedback-info: ${sky}15 !important;
  --background-feedback-notification: ${c.color1} !important;
  --badge-notification-background: ${c.color1} !important;
  --badge-text-brand: ${s.background} !important;
  --icon-feedback-positive: ${c.color2} !important;
  --icon-feedback-warning: ${c.color3} !important;
  --icon-feedback-critical: ${c.color1} !important;
  --icon-feedback-info: ${sky} !important;
  --icon-feedback-notification: ${c.color1} !important;
  --notice-background-critical: ${c.color1} !important;
  --notice-background-info: ${c.color4} !important;
  --notice-background-positive: ${c.color2} !important;
  --notice-background-warning: ${c.color3} !important;
  --notice-text-critical: ${crust} !important;
  --notice-text-info: ${crust} !important;
  --notice-text-positive: ${crust} !important;
  --notice-text-warning: ${crust} !important;
  --modal-background: ${s.background} !important;
  --modal-footer-background: ${s.background} !important;
  --card-background-default: ${surface0} !important;
  --custom-channel-members-bg: ${mantle} !important;
  --custom-status-bubble-background: ${crust} !important;
  --custom-status-bubble-background-color: ${mantle} !important;
  --logo-primary: ${s.foreground} !important;
  --white: ${s.foreground} !important;
  --white-500: ${s.foreground} !important;
  --black-500: ${crust} !important;
  --primary-100: ${subtext1} !important;
  --primary-200: ${subtext0} !important;
  --primary-300: ${subtext1} !important;
  --primary-400: ${subtext1} !important;
  --primary-630: ${surface0} !important;
  --primary-700: ${surface1} !important;
  --primary-800: ${crust} !important;
  --green-360: ${c.color2} !important;
  --green-300: ${c.color2} !important;
  --yellow-360: ${c.color3} !important;
  --yellow-300: ${c.color3} !important;
  --red-400: ${c.color1} !important;
  --red-430: ${adjustLightness(c.color1, -10)} !important;
  --red-500: ${adjustLightness(c.color1, -15)} !important;
  --blue-500: ${adjustLightness(c.color4, -10)} !important;
  --blue-530: ${adjustLightness(c.color4, -15)} !important;
  --plum-23: ${s.background} !important;
  --user-profile-overlay-background: ${mantle} !important;
  --user-profile-overlay-background-hover: ${surface0} !important;
  --__header-bar-background: ${mantle} !important;
  --__adaptive-focus-ring-color: ${accent} !important;`;

	const css = `/* Generated by novashell */
.visual-refresh.theme-dark,
.visual-refresh .theme-dark {
${vars}
}

.theme-dark {
${vars}
}
`;

	const vesktopDir = `${GLib.get_user_config_dir()}/vesktop/settings`;
	const vesktopDirFile = Gio.File.new_for_path(vesktopDir);
	if (!vesktopDirFile.query_exists(null)) {
		vesktopDirFile.make_directory_with_parents(null);
	}

	await writeFileAsync(`${vesktopDir}/quickCss.css`, css).catch((e: Error) => {
		console.error(`ColorUtils: Failed to write Vesktop theme: ${e.message}`);
	});
}

export async function updateYTMusicTheme(data: ColorData): Promise<void> {
	const c = data.colors;
	const s = data.special;
	const accent = data.accent || c.color4;

	const variables = `html:not(.style-scope)
{
  --ctp-rosewater: ${adjustLightness(c.color1, 50)};
  --ctp-flamingo: ${adjustLightness(c.color1, 30)};
  --ctp-pink: ${adjustLightness(c.color5, 30)};
  --ctp-mauve: ${c.color5};
  --ctp-red: ${c.color1};
  --ctp-maroon: ${adjustLightness(c.color1, 15)};
  --ctp-peach: ${adjustLightness(c.color3, 15)};
  --ctp-yellow: ${c.color3};
  --ctp-green: ${c.color2};
  --ctp-teal: ${c.color6};
  --ctp-sky: ${adjustLightness(c.color6, 15)};
  --ctp-sapphire: ${adjustLightness(c.color4, 15)};
  --ctp-blue: ${accent};
  --ctp-lavender: ${adjustLightness(accent, 25)};
  --ctp-text: ${s.foreground};
  --ctp-subtext1: ${adjustLightness(s.foreground, -15)};
  --ctp-subtext0: ${adjustLightness(s.foreground, -30)};
  --ctp-overlay2: ${adjustLightness(s.foreground, -50)};
  --ctp-overlay1: ${adjustLightness(s.foreground, -65)};
  --ctp-overlay0: ${adjustLightness(s.foreground, -80)};
  --ctp-surface2: ${adjustLightness(s.background, 40)};
  --ctp-surface1: ${adjustLightness(s.background, 25)};
  --ctp-surface0: ${adjustLightness(s.background, 15)};
  --ctp-base: ${s.background};
  --ctp-mantle: ${adjustLightness(s.background, -5)};
  --ctp-crust: ${adjustLightness(s.background, -10)};

  --ctp-accent: var(--ctp-blue);

  --unthemed-yet: inherit !important;

  --yt-spec-commerce-filled-hover: var(--ctp-accent) !important;
  --yt-spec-menu-background: var(--ctp-base) !important;

  --disabled-text-color: var(--ctp-surface0) !important;

  --ytmusic-scrollbar-width: 0px !important;
  --ytd-scrollbar-width: 0px !important;
}
`;

	let template: string;
	try {
		const bytes = Gio.resources_lookup_data(
			"/io/github/razen/novashell/templates/yt-music.css",
			null,
		);
		template = new TextDecoder().decode(bytes.get_data()!);
	} catch (e) {
		console.error(`ColorUtils: Failed to load YT Music template: ${e}`);
		return;
	}

	const fullCss = variables + template;

	const cacheDir = `${GLib.get_user_cache_dir()}/novashell`;
	const cacheDirFile = Gio.File.new_for_path(cacheDir);
	if (!cacheDirFile.query_exists(null)) {
		cacheDirFile.make_directory_with_parents(null);
	}

	await writeFileAsync(`${cacheDir}/yt-music-theme.css`, fullCss).catch((e: Error) => {
		console.error(`ColorUtils: Failed to write YT Music theme: ${e.message}`);
	});
}
