import Gio from "gi://Gio?version=2.0";
import GLib from "gi://GLib?version=2.0";

import { writeFileAsync } from "ags/file";
import { execAsync } from "ags/process";

import type { ColorData, DerivedPalette } from "./types";
import { adjustLightness } from "./utils";

async function cpInPlace(content: string, targetPath: string): Promise<void> {
	const tmpPath = `${GLib.get_tmp_dir()}/novashell-gtk-${GLib.get_monotonic_time()}`;
	await writeFileAsync(tmpPath, content);
	await execAsync(["cp", "--", tmpPath, targetPath]);
}

function ensureDir(path: string): void {
	const dir = Gio.File.new_for_path(path);
	if (!dir.query_exists(null)) {
		dir.make_directory_with_parents(null);
	}
}

export async function updateGtkColors(data: ColorData, p: DerivedPalette): Promise<void> {
	const s = data.special;
	const c = data.colors;

	const viewBg = adjustLightness(s.background, 8);
	const cardBg = adjustLightness(s.background, 13);
	const popoverBg = adjustLightness(s.background, 8);

	const css = `/* Generated by novashell - Theme: ${data.name || "pywal"} */
@define-color accent_bg_color ${p.accent};
@define-color accent_fg_color ${s.foreground};
@define-color accent_color ${p.accent};
@define-color destructive_bg_color ${c.color1};
@define-color destructive_fg_color ${s.foreground};
@define-color success_bg_color ${c.color2};
@define-color success_fg_color ${s.foreground};
@define-color warning_bg_color ${c.color3};
@define-color warning_fg_color ${s.background};
@define-color window_bg_color ${s.background};
@define-color window_fg_color ${s.foreground};
@define-color view_bg_color ${viewBg};
@define-color view_fg_color ${s.foreground};
@define-color headerbar_bg_color ${c.color0};
@define-color headerbar_fg_color ${s.foreground};
@define-color card_bg_color ${cardBg};
@define-color card_fg_color ${s.foreground};
@define-color dialog_bg_color ${s.background};
@define-color dialog_fg_color ${s.foreground};
@define-color popover_bg_color ${popoverBg};
@define-color popover_fg_color ${s.foreground};
@define-color sidebar_bg_color ${c.color0};
@define-color sidebar_fg_color ${s.foreground};
`;

	const themeDir = `${GLib.get_user_data_dir()}/themes/novashell`;
	const targets = [
		`${GLib.get_user_config_dir()}/gtk-4.0`,
		`${GLib.get_user_config_dir()}/gtk-3.0`,
		`${themeDir}/gtk-4.0`,
		`${themeDir}/gtk-3.0`,
	];

	for (const dir of targets) {
		ensureDir(dir);
	}

	const indexTheme = `[Desktop Entry]
Type=X-GNOME-Metatheme
Name=novashell

[X-GNOME-Metatheme]
GtkTheme=novashell
`;

	await Promise.all([
		...targets.map((dir) =>
			cpInPlace(css, `${dir}/gtk.css`).catch((e: Error) => {
				console.error(`ColorUtils: Failed to write ${dir}/gtk.css: ${e.message}`);
			}),
		),
		writeFileAsync(`${themeDir}/index.theme`, indexTheme).catch((e: Error) => {
			console.error(`ColorUtils: Failed to write theme index: ${e.message}`);
		}),
	]);
}
