# [[keyboard.bindings]]
# chars = """
# :Telescope git_files
# """
# key = "P"
# mods = "Command"
#
# [[keyboard.bindings]]
# chars = """
# :Telescope commands
# """
# key = "P"
# mods = "Command|Shift"
#
# [[keyboard.bindings]]
# chars = "\u0002L"
# key = "L"
# mods = "Command"

[general]
live_config_reload = true

[colors.bright]
black = "0xa6accd"
blue = "0xadd7ff"
cyan = "0x89ddff"
green = "0x5de4c7"
magenta = "0xfcc5e9"
red = "0xd0679d"
white = "0xffffff"
yellow = "0xfffac2"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "0x252b37"
blue = "0x89ddff"
cyan = "0xadd7ff"
green = "0x5de4c7"
magenta = "0xfae4fc"
red = "0xd0679d"
white = "0xffffff"
yellow = "0xfffac2"

[colors.primary]
background = "0x252b37"
foreground = "0xa6accd"

[colors.search.focused_match]
background = "0xadd7ff"
foreground = "0x1b1e28"

# [colors.search.footer_bar]
# background = "0xadd7ff"
# foreground = "0x1b1e28"

[colors.search.matches]
background = "0xadd7ff"
foreground = "0x1b1e28"

[colors.selection]
background = "0x303340"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[env]
TERM = "xterm-256color"

[font]
size = 22.0

[font.normal]
# family = "SFMono Nerd Font"
# family = "JetBrainsMono Nerd Font"
family = "Monaspace Xenon"
style = "Medium"

# [font.italic]
# style = "Medium"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',│`|:"' ()[]{}<>	'''

[window]
blur = true
option_as_alt = "Both"
decorations = "buttonless"
dynamic_padding = false
opacity = 0.8

# [window.dimensions]
# columns = 120
# lines = 30

[window.padding]
x = 18
y = 16

[keyboard]
