#
# ███████╗██╗███████╗██╗  ██╗
# ██╔════╝██║██╔════╝██║  ██║
# █████╗  ██║███████╗███████║
# ██╔══╝  ██║╚════██║██╔══██║
# ██║     ██║███████║██║  ██║
# ╚═╝     ╚═╝╚══════╝╚═╝  ╚═╝
# A smart and user-friendly command line
# https://fishshell.com/

if test -x /opt/homebrew/bin/brew
    eval (/opt/homebrew/bin/brew shellenv fish)
    set -x HOMEBREW_AUTOREMOVE 1
end

if test -d "/run/user/"(id -u)"/hypr"
    set -gx HYPRLAND_INSTANCE_SIGNATURE (ls -t /run/user/(id -u)/hypr/ 2>/dev/null | head -1)
end

starship init fish | source # https://starship.rs/
zoxide init --cmd cd fish | source # 'ajeetdsouza/zoxide'
fx --comp fish | source # https://fx.wtf/

if type -q mise
    mise activate fish | source
end

set -U fish_greeting # disable fish greeting
# i don't use vi mode in fish
# set -U fish_key_bindings fish_vi_key_bindings

set -Ux SUDO_EDITOR nvim
set -Ux EDITOR nvim
# fzf configuration is in conf.d/fzf.fish

if test (uname) = Darwin
    set -x PNPM_HOME "$HOME/Library/pnpm"
else
    set -x PNPM_HOME "$HOME/.local/share/pnpm"
end
fish_add_path $PNPM_HOME
if type -q pnpm
    fish_add_path (pnpm --global bin)
end

fish_add_path "$HOME/.opencode/bin"
fish_add_path "$HOME/.bun/bin"
fish_add_path "$HOME/.cache/.bun/bin"

set -x XDG_CONFIG_HOME "$HOME/.config"

fish_add_path "$HOME/.local/bin" # local bin
fish_add_path "$HOME/.config/bin" # my custom scripts
fish_add_path "$HOME/codelldb/extension/adapter" # codelldb

fish_add_path ~/.global-python/bin # python global installs using uv

# view man pages using Neovim
set -Ux MANPAGER "nvim +Man!"

# Source pywal colors if available (generated by novashell)
if test -f ~/.cache/wal/colors.fish
    source ~/.cache/wal/colors.fish
end

# Fallback to catppuccin if no pywal colors
# fish_config theme choose Dracula
# fish_config theme choose tokyonight
# fish_config theme choose catppuccin
