# @generated by usage-cli from /home/razen/projects/dotfiles/novashell/nsh-msg.usage.kdl

# quietly skip dynamic completions when usage is unavailable
if ! type -p usage &> /dev/null
    return 0
end

set _usage_spec_nsh_msg 'name "Novashell Socket CLI"
bin nsh-msg
about "Fast socket commands for Novashell"
cmd help help="Show nsh-msg usage" {
    alias h
}
cmd open help="Open a shell window" {
    arg <window> help="Window name to open"
}
cmd close help="Close a shell window" {
    arg <window> help="Window name to close"
}
cmd toggle help="Toggle a shell window" {
    arg <window> help="Window name to toggle"
}
cmd reopen help="Reopen currently open windows"
cmd reload help="Restart Novashell instance"
cmd quit help="Quit Novashell main instance"
cmd runner help="Toggle app runner window" {
    arg "[initial_text]" help="Optional initial runner query" required=#false
}
cmd run help="Launch app or alias" {
    arg <app_or_alias> help="Application id/command or %alias"
    arg "[client_modifiers]" help="Optional Hyprland client modifiers" required=#false
}
cmd peek-workspace-num help="Temporarily show workspace numbers" {
    arg "[millis]" help="Duration in milliseconds" required=#false
}
cmd volume help="Control sink/source volume" {
    cmd sink-set help="Set sink volume" {
        arg <value> help="Volume percent integer"
    }
    cmd source-set help="Set source volume" {
        arg <value> help="Volume percent integer"
    }
    cmd sink-mute help="Toggle sink mute"
    cmd source-mute help="Toggle source mute"
    cmd sink-increase help="Increase sink volume" {
        arg <value> help="Volume delta integer"
    }
    cmd source-increase help="Increase source volume" {
        arg <value> help="Volume delta integer"
    }
    cmd sink-decrease help="Decrease sink volume" {
        arg <value> help="Volume delta integer"
    }
    cmd source-decrease help="Decrease source volume" {
        arg <value> help="Volume delta integer"
    }
}
cmd media help="Control active media player" {
    cmd play help="Play media"
    cmd pause help="Pause media"
    cmd play-pause help="Toggle play/pause"
    cmd stop help="Stop media"
    cmd previous help="Previous track"
    cmd next help="Next track"
    cmd select help="Select active player by bus name" {
        arg <bus_name> help="MPRIS bus name"
    }
}
cmd theme help="Manage Novashell themes" {
    cmd set help="Apply theme by id" {
        arg <theme_id> help="Theme id"
    }
    cmd sync help="Sync colors from current wallpaper (pywal mode only)"
}
cmd wallpaper help="Manage wallpaper" {
    cmd set help="Set wallpaper and sync colors when applicable" {
        arg <path> help="Wallpaper path"
    }
    cmd set-only help="Set wallpaper without syncing colors" {
        arg <path> help="Wallpaper path"
    }
    cmd pick help="Open wallpaper picker"
}
cmd dev help="Development/debug helpers" {
    cmd inspector help="Open GTK inspector"
}
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_nsh_msg.spec"
echo $_usage_spec_nsh_msg > "$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc nsh-msg -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc nsh-msg -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
