monitor.alsa.rules = [
    {
        matches = [
            { node.name = "~alsa_*" }
        ]
        actions = {
            update-props = {
                api.alsa.period-size   = 1024
                api.alsa.headroom      = 8192
                session.suspend-timeout-seconds = 0
            }
        }
    }
]
