monitor.alsa.rules = [
    {
        matches = [
            { node.name = "alsa_input.usb-Razer_Inc_Razer_Kiyo_Pro-02.analog-stereo" }
        ]
        actions = {
            update-props = {
                node.disabled = true
            }
        }
    }
]
